function result=vertexesOfBox(pos_center_obs, half_side_bbox)

        result=[pos_center_obs + half_side_bbox*[1;1;1] ...
                pos_center_obs + half_side_bbox*[1;1;-1] ...
                pos_center_obs + half_side_bbox*[1;-1;1] ...
                pos_center_obs + half_side_bbox*[1;-1;-1] ...
                pos_center_obs + half_side_bbox*[-1;1;1] ...
                pos_center_obs + half_side_bbox*[-1;1;-1] ...
                pos_center_obs + half_side_bbox*[-1;-1;1] ...
                pos_center_obs + half_side_bbox*[-1;-1;-1]];

end