function result=vertexesOfBox(pos_center_obs, obstacle_bbox)

        obstacle_half_bbox=obstacle_bbox/2.0;

        result=[pos_center_obs + obstacle_half_bbox.*[1;1;1] ...
                pos_center_obs + obstacle_half_bbox.*[1;1;-1] ...
                pos_center_obs + obstacle_half_bbox.*[1;-1;1] ...
                pos_center_obs + obstacle_half_bbox.*[1;-1;-1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;1;1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;1;-1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;-1;1] ...
                pos_center_obs + obstacle_half_bbox.*[-1;-1;-1]];

end