function result=vertexesOfBox(pos_center_obs, obstacle_bbox)
        obstacle_half_bbox=obstacle_bbox/2.0;
        dim = size(obstacle_half_bbox, 1);

        if dim == 2
                result=[pos_center_obs + obstacle_half_bbox.*[1;1] ...
                        pos_center_obs + obstacle_half_bbox.*[1;-1] ...
                        pos_center_obs + obstacle_half_bbox.*[-1;-1] ...
                        pos_center_obs + obstacle_half_bbox.*[-1;1]];
        else
                result=[pos_center_obs + obstacle_half_bbox.*[1;1;1] ...
                        pos_center_obs + obstacle_half_bbox.*[1;1;-1] ...
                        pos_center_obs + obstacle_half_bbox.*[1;-1;1] ...
                        pos_center_obs + obstacle_half_bbox.*[1;-1;-1] ...
                        pos_center_obs + obstacle_half_bbox.*[-1;1;1] ...
                        pos_center_obs + obstacle_half_bbox.*[-1;1;-1] ...
                        pos_center_obs + obstacle_half_bbox.*[-1;-1;1] ...
                        pos_center_obs + obstacle_half_bbox.*[-1;-1;-1]];
        end
end